[package]
name = "kneron_bbox_server_node"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
clap = { version = "4.0.11", features = ["derive"] }
kneron_bbox_server = { version = "0.1.0", path = "../kneron_bbox_server" }
r2r = "0.6.3"
