[package]
name = "kneron-bbox-server-node"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
kneron-bbox-server = { version = "0.1.0", path = "../kneron-bbox-server" }
r2r = "0.6.3"
